create table if not exists public.article_seo_optimizations (
  article_id uuid primary key references public.logbook_articles(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'ready', 'failed')),
  source_hash text,
  model text,
  generated_at timestamptz,
  error_message text,
  title_it text,
  title_en text,
  description_it text,
  description_en text,
  social_title_it text,
  social_title_en text,
  social_description_it text,
  social_description_en text,
  keywords_it text[] not null default '{}',
  keywords_en text[] not null default '{}',
  image_alt_it text,
  image_alt_en text,
  structured_data jsonb not null default '{}'::jsonb,
  recommendations jsonb not null default '{}'::jsonb,
  raw_response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

comment on table public.article_seo_optimizations is
  'AI-generated SEO optimization for published logbook articles. Generated by the optimize-article-seo Edge Function.';

create index if not exists article_seo_optimizations_status_idx
  on public.article_seo_optimizations(status, updated_at desc);

create or replace function public.touch_article_seo_optimizations_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists article_seo_optimizations_touch_updated_at on public.article_seo_optimizations;
create trigger article_seo_optimizations_touch_updated_at
before update on public.article_seo_optimizations
for each row execute function public.touch_article_seo_optimizations_updated_at();

alter table public.article_seo_optimizations enable row level security;

drop policy if exists "Published article SEO is publicly readable" on public.article_seo_optimizations;
create policy "Published article SEO is publicly readable"
on public.article_seo_optimizations
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.logbook_articles a
    where a.id = article_id
      and a.status = 'published'
  )
);

drop policy if exists "Admins can manage article SEO" on public.article_seo_optimizations;
create policy "Admins can manage article SEO"
on public.article_seo_optimizations
for all
to authenticated
using ((select public.has_role((select auth.uid()), 'admin')))
with check ((select public.has_role((select auth.uid()), 'admin')));
