// This file is automatically generated. Do not edit it directly.
import type { Database } from "./types";
import { createBiteSupabaseClient } from "@shared/supabase/create-client";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createBiteSupabaseClient<Database>({ passkey: true });
