/**
 * Same-domain proxy for the dynamic LLM discovery feed generated by the
 * Supabase `public-llms` edge function.
 *
 * Exposed as /llms.txt and /llms-full.txt via rewrites in vercel.json so AI
 * user agents discover current articles, voyages, and public URLs on the
 * canonical host.
 */

const FALLBACK_SUPABASE_URL = "https://ekwloweuicrqjjgabfdp.supabase.co";

interface NodeRequest {
  url?: string;
}

interface NodeResponse {
  statusCode: number;
  setHeader(name: string, value: string): void;
  end(body: string): void;
}

export default async function handler(req: NodeRequest, res: NodeResponse): Promise<void> {
  const baseUrl = process.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
  const url = new URL(req.url || "/", "https://biteproject.it");
  const full = url.searchParams.get("full") === "1" || url.searchParams.get("path") === "/llms-full.txt";

  try {
    const response = await fetch(`${baseUrl}/functions/v1/public-llms${full ? "?full=1" : ""}`);
    if (!response.ok) {
      res.statusCode = 502;
      res.end("LLMs feed upstream error");
      return;
    }
    const text = await response.text();
    res.statusCode = 200;
    res.setHeader("Content-Type", "text/markdown; charset=utf-8");
    res.setHeader("Cache-Control", "public, s-maxage=3600, stale-while-revalidate=86400");
    res.end(text);
  } catch {
    res.statusCode = 502;
    res.end("LLMs feed upstream unreachable");
  }
}
