/**
 * Same-domain proxy for the dynamic sitemap generated by the Supabase
 * `public-sitemap` edge function. The Supabase functions gateway rewrites XML
 * content types to text/plain; serving it from biteproject.it restores the
 * proper application/xml header and keeps the sitemap on the canonical host.
 *
 * Exposed as /sitemap-live.xml via the rewrite in vercel.json.
 */

const FALLBACK_SUPABASE_URL = "https://ekwloweuicrqjjgabfdp.supabase.co";

interface NodeResponse {
  statusCode: number;
  setHeader(name: string, value: string): void;
  end(body: string): void;
}

export default async function handler(_req: unknown, res: NodeResponse): Promise<void> {
  const baseUrl = process.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;

  try {
    const response = await fetch(`${baseUrl}/functions/v1/public-sitemap`);
    if (!response.ok) {
      res.statusCode = 502;
      res.end("Sitemap upstream error");
      return;
    }
    const xml = await response.text();
    res.statusCode = 200;
    res.setHeader("Content-Type", "application/xml; charset=utf-8");
    res.setHeader("Cache-Control", "public, s-maxage=3600, stale-while-revalidate=86400");
    res.end(xml);
  } catch {
    res.statusCode = 502;
    res.end("Sitemap upstream unreachable");
  }
}
